name: CI/CD

on:
    push:
        branches:
            - main
env:
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: install node.js 22
              uses: actions/setup-node@v3
              with:
                 node-version: '22'
            - name: install dependencies
              run: yarn install

            - name: Build project
              run: yarn build
    Deploy:
        needs: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: install node.js 22
              uses: actions/setup-node@v3
              with:
                 node-version: '22'
            - name: install vercel CLI
              run: yarn global add vercel
            - name: Pull vercel Environment variables
              run: vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }}
            - name: Deploy to Vercel
              run: vercel deploy --no-wait --token ${{ secrets.VERCEL_TOKEN }}